apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-test
spec:
  replicas: 1
  selector:
    app: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins
        ports:
        - containerPort: 80
