apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    name: nginx-rs
  name: nginx-rs   
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rs-pod
  template:
    metadata:
      labels:
        app: nginx-rs-pod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 81
          name: http
          protocol: TCP        
